/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef demo_CONSTANTS_H
#define demo_CONSTANTS_H

#include "demo_types.h"

namespace demo {

class demoConstants {
 public:
  demoConstants();

};

extern const demoConstants g_demo_constants;

} // namespace

#endif
