/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "demo_constants.h"

namespace demo {

const demoConstants g_demo_constants;

demoConstants::demoConstants() {
}

} // namespace

